### PR TITLE
Milestone 3. 

### PR DESCRIPTION
**Pull request by sergiocortessat**
Hello TSE

Pull request for Milestone 3. We tried to implement a method for mutual friends which is included in the helper and pass to the view.

NOTE: We are somehow confused on what is exactly wanted as per "implement friendships with 2 rows for mutual friendship". Therefore we have added a mutual method array in helper to display common friends. 

NOTe: There is just one commit as we just needed to modify one method.

- Added mutual_btn to helper and display mutual friends.
- Added unit and integration test to check friendships requests

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on**. However, there are a few issues to fix to get approved. I will explain to you what exactly is needed in this milestone.

### REQUIRED CHANGES: ⚠️ 

> The main goal of creating two rows is to optimize the db table for the users friend's list. Read more about this concept [here](https://explainextended.com/2009/03/07/selecting-friends) and [here](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table)

- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created. 
Thanks to this, we can find user friends only by user_id in friendships table `has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"`

- [x] User #pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby). This will replace this method 👉🏽 `pending_friends`
- [x] User #friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby). This will replace this method 👉🏽 `friend_requests`
- [x] Remember to add new tests(unit and integration) once you implement these changes.

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Ping me on slack for a chit-chat 🆘  Roy Mukuye Or mention me in this PR

**Comment by sergiocortessat** [comment]
Pull request 2.

We have added the requested changes to modify the user model associations.

- Confirmed friendships
- Pending friendships
- Inverse friendships
- Test for new associations

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

Hello @sergiocortessat and @nganifaith, Great job! 👏  Both of you have done an awesome job.
✔️ Your ReadMe file is looking professional
✔️ Excellent job on the specs
✔️ Great job on eliminating all logic from views

Let's make a few changes, and we will be done.

### Behavior

- [x] Kindly update the `sign_up` button on the top bar with the correct url, throws an error when clicked 
Screen Shot 2021-04-13 at 4 58 08 PM

- [x] When I accept a friend request, I noticed I have to also send another request to the user and he/she has to accept as well before I can become friends with him. I do not need to send another request before becoming friends.

### Controller

- [x] You have the code below in your friendship model
```ruby
def confirm_friend
    update_attributes(confirmed: true)
    Friendship.create!(friend_id: user_id,
                       user_id: friend_id,
                       confirmed: true)
  end
```
I noticed you've not used it anywhere in your code instead you created similar method again in your confirm method inside friendships_controller. Consider refactoring your `#confirm` method to use `#confirm_friend`.
You can consider having it inside your user model

```ruby
# app/model/user.rb

  def confirm_friend(user)
    friend = Friendship.find_by(user_id: user.id, friend_id: id)
    friend.confirmed = true
    friend.save
    Friendship.create!(friend_id: user.id, user_id: id, confirmed: true)
  end

```
And your confirm method inside users_controllers should look like
```ruby
def confirm
    @user = User.find(params[:id])

    if current_user.confirm_friend(@user)
      redirect_to root_path
      flash[:notice] = 'Friend request accepted'
    else
      redirect_to root_path
      flash[:alert] = 'something went wrong with accepting the invite.'
    end
  end
```
Now we no longer have redundant code.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by sergiocortessat** [comment]
Pull request 3.

We have added all requested changes
- Signup link fixed on _header
- Friends are being automatically added once a request is sent and accepted
- We have moved the redundant code out of user_controller into the user model. Now it calls the method inside the controller.

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Excellent job team!
Everything looks great.

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next milestone.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
